packages:
    py-giss:
        version: [develop]
        variants: [~plot]

    # Chinook uses OpenMPI
    # This has been moved to tw-chinook/spack.yaml
#    openmpi:
#        paths:
#            openmpi@4.0.2: /opt/scyld/openmpi/4.0.2/intel
#            openmpi@3.1.4: /opt/scyld/openmpi/3.1.4/intel
#        version: [3.1.4,4.0.2]   # Don't choose version for the user
#        buildable: False
    intel-mkl:
        paths:
            intel-mkl@2018.4.274: /usr/local/pkg/compiler/icc/2018.5.274-GCC-5.4.0-2.26/compilers_and_libraries_2018.5.274/linux/mkl/lib
        version: [2018.4.274]
        buildable: False

    # Intel 18 doesn't support features needed by Freetype 2.9
    # https://github.com/spack/spack/issues/13984
    freetype:
        version: [2.7.1]

    all:
        variants: [+python3]
        compiler: [intel@18.5.274]
        providers:
            mpi: [openmpi]
            blas: [intel-mkl]
            lapack: [intel-mkl]
            scalapack: [intel-mkl]
            mkl: [intel-mkl]
            fftw-api: [intel-mkl]

#            blas: [openblas]
#            lapack: [openblas]

