packages:
# Commented-out items need to be added back to oneway-discover
#    modele:
#        variants: [~tests,~everytrace]
#
#    modele-control:
#        version: [develop]
    py-giss:
        version: [develop]
        variants: [~plot]
#    python:
#        variants: [~pythoncmd]
#        version: [3.5.2]
    intel-mpi:
        paths:
            intel-mpi@2018.4.274: /usr/local/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi
        version: [2018.4.274]
        buildable: False
    intel-mkl:
        paths:
            intel-mkl@2018.4.274: /usr/local/intel/2018/compilers_and_libraries_2018.5.274/linux/mkl
        version: [2018.4.274]
        buildable: False

    # Intel 18 doesn't support features needed by Freetype 2.9
    # https://github.com/spack/spack/issues/13984
    freetype:
        version: [2.7.1]

    all:
        variants: [+python3]
        compiler: [intel@18.0.4]
        providers:
            mpi: [intel-mpi]
            blas: [intel-mkl]
            lapack: [intel-mkl]
            scalapack: [intel-mkl]
            mkl: [intel-mkl]
            fftw-api: [intel-mkl]

#            blas: [openblas]
#            lapack: [openblas]

