packages:
    modele:
        variants: [~tests,~everytrace]

    modele-control:
        version: [develop]
    py-giss:
        version: [develop]
        variants: [~plot]
    python:
        variants: [~pythoncmd]
        version: [3.5.2]
    intel-mpi:
        paths:
            intel-mpi@2018.4.274: /usr/local/intel/2018/compilers_and_libraries_2018.5.274/linux/mpi
        version: [2018.4.274]
        buildable: False
    all:
        variants: [+python3]
        compiler: [intel@18.0.4]
        providers:
            mpi: [intel-mpi]
#            blas: [openblas]
#            lapack: [openblas]

